TrabajoFinal: TrabajoFinal.o TrabajoFinalTest.o
	g++ TrabajoFinal.o TrabajoFinalTest.o -o TrabajoFinal 

TrabajoFinal.o: TrabajoFinal.cpp
	g++ -c TrabajoFinal.cpp

TrabajoFinalTest.o: TrabajoFinalTest.cpp
	g++ -c TrabajoFinalTest.cpp