StreamArray: StreamArray.o StreamArrayTest.o
	g++ StreamArray.o StreamArrayTest.o -o StreamArray 

StreamArray.o: StreamArray.cpp
	g++ -c StreamArray.cpp

StreamArrayTest.o: StreamArrayTest.cpp
	g++ -c StreamArrayTest.cpp